### ISSUE TITLE
Glimmer & Gloom Solver Question

### ISSUE THREAD

**Issue by Seeje-y** [LegoFigure11/legofigure11.github.io#24]
Hi! Thank you so, so much for this tool! It was perfect untill a couple days ago, but, now, the middle line has shifted a bit to the left while both the one above it and the one below it are shifted to the right which isn't much, but makes it harder to figure out which tiles are the ones highlighted and, sometimes the highlights don't show up at all after I input which tiles I still have left in the game and I have to refresh the page for the highlights to show up.

I hope everything is alright and that the tool can be perfect, again, as it had been for so long.

**Comment by LegoFigure11** [comment]
Hi! e2016d0 introduced a new board layout, and I'm assuming that's what you're referring to here. Using the display mode drop-don menu, you should be able to select "Classic" to exactly replicate the old behavior.
![image](https://github.com/user-attachments/assets/ebf0d3c7-2e37-465b-b89e-e5097069ce0a)

Closing this as I can't find any differences between classic and before that commit, but feel free to re-open with screenshots if you're still having issues!
